contentratio = 0.8
readMore = true
customCss = ['css/notices.css', 'css/tagcloud.css', 'css/highlight.css', 'css/search.css', 'css/commons.css']
enableMediumZoom = false

title = "Basics & Beyond"
author = "Basics & Beyond"
description = "Intellisense Every Programmer Needs"
profilePicture = "favicon.png"